CREATE TABLE todos (
	todo_id INT AUTO_INCREMENT PRIMARY KEY
	,title VARCHAR(50) NOT NULL
	,detail TEXT NOT NULL
	,deadline DATETIME NOT NULL
	,state ENUM('NOT_DONE','DONE') NOT NULL DEFAULT 'NOT_DONE'
	,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);